project:
  type: book
  output-dir: _book

book:
  title: "Open Music Registers: Economy & Business"
  subtitle: Coordinating regisers and registration processes for economic measurements
  author:
     - name: "Daniel Antal, CFA"
       orcid: 0000-0001-7513-6760
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
     - name: "Richard Demčák"
       orcid: 0009-0007-0687-1201
       affiliations:
               - name: SOZA
                 url: https://soza.sk/
     - name: "Asmah Federico"
       orcid: 0009-0004-7206-4174
     - affiliations:
               - name: Reprex
               - url: https://reprex.nl/
     - name: "Matej Grochal"
     - orcid:
     - affiliations:
               - name: Wikimedia Foundation
               - url:
     - name: "Marián Jankovič"
     - orcid: 0009-0003-6326-226X
     - affiliations:
               - name: SOZA
               - url: https://soza.sk/
     - name: "Anna Márta Mester"
       orcid: 0009-0008-2274-8163
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
     - name: "Edīte Punka"
     - orcid: https://orcid.org/0009-0003-7184-4155
     - affiliations:
               - name: Reprex
               - url: https://reprex.nl/
     - name: "Anna Žilková"
     - orcid: 0009-0007-5261-6930
     - affiliations:
               - name: Music Center Slovakia
               - url: https://hc.sk/
  date: today
  doi: 10.5281/zenodo.14767717
  repo-url: https://github.com/dataobservatory-eu/music-economy-register
  repo-actions: [edit]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - glossary.qmd
    - ambition.qmd
    - working.qmd
    - surveying.qmd
    - references.qmd
  appendices: 
    - t12.qmd
    - appendix-how_to_use.qmd
#    - appendix-register.qmd

version: 0.2.0

bibliography: 
    - bib/administrativedata.bib
    - bib/antal.bib
    - bib/cm.bib
    - bib/collections.bib
    - bib/datagovernance.bib
    - bib/datamodels.bib
    - bib/dataspace.bib
    - bib/ddi.bib
    - bib/ddex.bib
    - bib/eulaw.bib
    - bib/identifiers.bib
    - bib/ILO.bib
    - bib/ISOdata.bib
    - bib/KULT.bib
    - bib/metadata.bib
    - bib/musiceducation.bib
    - bib/musicidentifiers.bib
    - bib/nerd.bib
    - bib/OpenMusE.bib
    - bib/ontologies.bib
    - bib/privatelyhelddata.bib
    - bib/registers.bib
    - bib/wikidata.bib
    - bib/esco_nace.bib
    - bib/eosc.bib
    - bib/eccch.bib
    - bib/thesauri.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub: default 
  docx: 
    reference-doc: docx/OpenMusE_simple_template.docx

editor: visual

